# Advanced MLP network configuration
name: "advanced_mlp"
input_dim: 2
hidden_dim: 64
num_hidden_layers: 6
use_layer_norm: true
use_skip_connections: true
activation: "leaky_relu"
leaky_relu_slope: 0.02 