# VE (Variance Exploding) preconditioning configuration
name: 've'
sigma_data: 0.5    # Expected standard deviation of the training data
sigma_min: 0.02    # Minimum noise level
sigma_max: 100.0   # Maximum noise level 